import Head from "next/head";
import HamburgerMenu from "../components/HamburgerMenu";
import Main from "../components/Main";
import MainHeader from "../components/MainHeader";
import Nav from "../components/Nav";
import Pagination from "../components/Pagination";
import SelectDropdown from "../components/SelectDropdown";
import TopSection from "../components/TopSection";
import useWindowWidth from "../hooks/useWindowWidth";

export default function Home() {
  const [width] = useWindowWidth();
  return (
    <div className="flex p-4 bg-[#1C3FAA] min-h-screen overflow-hidden">
      <Head>
        <title>Pickvibe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {width >= 920 ? (
        <aside>
          <Nav />
        </aside>
      ) : (
        <HamburgerMenu />
      )}
      <div className="flex flex-col bg-gray-100 w-full rounded-2xl p-4">
        <MainHeader />
        <TopSection />
        <Main />
        <div className="flex flex-col md:flex-row md:justify-between md:items-start items-center p-2 ">
          <Pagination />
          <div className="flex justify-center md:justify-end md:my-0 my-4">
            <SelectDropdown />
          </div>
        </div>
      </div>
    </div>
  );
}
